Renderboard
wathigo/Tic-tac-toe-js pull request #3
Opened 2019-10-24 11:28 UTC by samgaco

2019-10-24 13:29 UTC, JamesOkunlade requested changes
# Changes required 😁 

**Good job so far. Here are some changes you'll need to implement to get a thumb up 🙂** 

- Separate your different modules into different files. `Gameboard`, `Player` and a `domManager`. You can then import different files in the different places you need them. Ensure to use `ES6 import` statement rather than `require`. 
- The essence of the `domManager` is to manipulate the dom. So you shouldn't mix your game logic with any dom-manipulation task. All dom-manipulation tasks should be done in the `domManager` only.
- I left some comments on your code as well, implement the changes I requested there too.

**Please implement those and request a re-review when you're done. 😄** 

**James Okunlade**
**Happy coding! 😎**

2019-10-24 13:29 UTC, JamesOkunlade commented on css/styles.css
> +} */
Don't leave unused code as a comment in your codebase. Remove them if they are not needed.

2019-10-24 13:29 UTC, JamesOkunlade commented on css/styles.css
> +} */
Don't leave unused code as a comment in code.

2019-10-24 13:29 UTC, JamesOkunlade commented on index.html
> +    <script src="./js/player.js" type="module"></script> -->
Remove this as well.

2019-10-24 13:29 UTC, JamesOkunlade commented on js/script.js
> +})();
As I have summarized in my first point of the general review, this should be in a file of its own. You can then import it into any file you want to call it from.

2019-10-24 15:22 UTC, JamesOkunlade requested changes
# Changes required 😁 

An error is preventing your game from starting. Check your `console` to see and fix the error.

Request for another review when you're done.

**James Okunlade**
**Happy coding!**

2019-10-24 15:28 UTC, samgaco commented
Hi, Would it be possible to get some indications? We are not sure about how to solve this problem or what is causing the errors.

2019-10-24 15:34 UTC, JamesOkunlade commented
![image](https://user-images.githubusercontent.com/26285695/67501359-0f06eb00-f67c-11e9-8117-79d399115f96.png)
There you go.

2019-10-24 15:49 UTC, samgaco commented
We get the same errors and googling, those are gone by running a [server](https://jasonwatmore.com/post/2016/06/22/nodejs-setup-simple-http-server-local-web-server) once we run the server we get other errors that we are clueless on how to solve. Should the project be able to be launched with no local server?

2019-10-25 09:14 UTC, JamesOkunlade approved these changes
# Approved 👍 😄 

**Go ahead and merge. Good luck with your future projects. 😎** 

**James Okunlade**
**Happy coding! 😎**

2019-10-25 09:15 UTC, wathigo commented
Thank you @JamesOkunlade

2019-10-25 09:16 UTC, merged